config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, path: 'admin', controllers: {
    sessions: 'admin/users/sessions'
  }
  root 'homes#index'

  namespace :admin do
    resources :posts
    resources :categories
    resources :quotes
    resources :contacts
  end

  resources :posts, only: [:index, :show]
  resources :homes, only: [:index]
  resources :contacts, only: [:index, :create]
  resources :category, only: [:index, :show]
  resources :abouts, only: [:index]
  resources :static_pages do
    collection do
      get 'single'
      get 'contact'
      get 'gallery'
    end
  end

end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string
#  slug       :string
#  show_menu  :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  PARAMS = [:name, :show_menu]

  has_many :posts

  belongs_to :user

  validates :name, :show_menu, presence: true
end

app/models/contact.rb
# == Schema Information
#
# Table name: contacts
#
#  id          :integer          not null, primary key
#  email       :string
#  lastname    :string
#  firstname   :string
#  description :text
#  read        :boolean
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Contact < ActiveRecord::Base
  PARAMS = [:email, :lastname, :firstname, :description]
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id          :integer          not null, primary key
#  title       :string
#  content     :text
#  date_post   :datetime
#  number_view :integer
#  url_image   :string
#  recommend   :boolean
#  public      :boolean
#  description :string
#  slug        :string
#  user_id     :integer
#  category_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  before_create :add_date_post

  PARAMS = [:title, :content, :description, :date_post, :url_image, :recommend, :public, :category_id]

  belongs_to :user
  belongs_to :category

  delegate :name, to: :category, prefix: true, allow_nil: true
  delegate :email, to: :user, prefix: true, allow_nil: true

  validates :title, :description, :content, :category_id, presence: true

  def add_date_post
    self.date_post = DateTime.current
  end
end

app/models/quote.rb
# == Schema Information
#
# Table name: quotes
#
#  id         :integer          not null, primary key
#  content    :string
#  author     :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Quote < ActiveRecord::Base
end

app/models/subcribe.rb
# == Schema Information
#
# Table name: subcribes
#
#  id         :integer          not null, primary key
#  email      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Subcribe < ActiveRecord::Base
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :async,
         :recoverable, :rememberable, :trackable

  has_many :posts
  has_many :categories
  has_one :user_detail

  accepts_nested_attributes_for :user_detail, allow_destroy: true
end

app/models/user_detail.rb
# == Schema Information
#
# Table name: user_details
#
#  id           :integer          not null, primary key
#  first_name   :string
#  last_name    :string
#  phone_number :string
#  address      :string
#  sex          :string
#  user_id      :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class UserDetail < ActiveRecord::Base
  belongs_to :user
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
end

app/controllers/admin_controller.rb
class AdminController < ActionController::Base
  before_action :authenticate_user!

  layout 'admin_lte_2'
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :load_service

  def index
    @q              = @service.condition(params)
    @posts          = @service.all_post(params)
    @post_recommend = @service.recommend_post
    @post_random    = @service.random_post
    @post_most_view = @service.most_view_post
    @quotes         = @service.quotes
  end

  private
    def load_service
      @service = HomeService.new
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def show
    @post = Post.friendly.find(params[:id])
    @post.update(number_view: @post.number_view.to_i + 1)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
  def gravatar_url(email, size)
    gravatar = Digest::MD5::hexdigest(email).downcase
    url = "http://gravatar.com/avatar/#{gravatar}.png?s=#{size}"
  end

  def active_menu controller_name, name
    controller_name == name ? 'active' : ''
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_menu controller_name, name
    controller_name == name ? 'active' : ''
  end

  def convert_date date
    date.strftime('%b %d, %Y')
  end
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admin/shared/_errors.html.slim
.has-error
  - object.errors.full_messages.each do |full_message|
    span.help-block
      = full_message

app/views/shared/_footer.html.slim
.footer
  .container
    .footer-text
      .fb-like[data-href="http://trungkienit.com/" data-layout="button_count" data-action="like" data-size="small"]
    .footer-text
      p
        | © 2015 Coffee Break. All Rights Reserved | Design by 
        a[href="http://w3layouts.com/" target="_blank"]
          | W3layouts

app/views/shared/_header.html.slim
/ - if controller_name == 'homes'
  .header-top
    .container
      .head-main
        = link_to root_path
          = image_tag 'logo-1.png'
.header
  .container
    .head
      .navigation
        span.menu
        ul.navig
          li
            = link_to t('header.home'), root_path, class: (active_menu('homes', controller_name))
          / li
            = link_to t('header.about'), abouts_path, class: (active_menu('abouts', controller_name))
          li
            = link_to t('header.gallery'), category_index_path, class: (active_menu('category', controller_name))
          - if @menus
            - @menus.each do |menu|
              li
                = link_to menu.name, menu, class: (active_menu("category_#{menu.slug}", "#{controller_name}_#{menu.slug}"))
          li
            = link_to t('header.contact'), contacts_path, class: (active_menu('contacts', controller_name))
      .header-right
        .search-bar
          = search_form_for @q, url: root_path do |f|
            = f.text_field :title_cont, placeholder: 'Search'
            input[type="submit" value=""]
        ul
          li
            a[href="https://www.facebook.com/nguyentrungkienkbang"]
              span.fb
          li
            a[href="#"]
              span.twit
          li
            a[href="#"]
              span.pin
          li
            a[href="#"]
              span.rss
          li
            a[href="#"]
              span.drbl
      .clearfix