config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, path: 'admin', controllers: {
    sessions: 'admin/users/sessions'
  }
  root 'homes#index'

  namespace :admin do
    resources :posts
    resources :categories
    resources :quotes
    resources :contacts
  end

  resources :posts, only: [:index, :show]
  resources :homes, only: [:index]
  resources :contacts, only: [:index, :create]
  resources :category, only: [:index, :show]
  resources :abouts, only: [:index]
  resources :static_pages do
    collection do
      get 'single'
      get 'contact'
      get 'gallery'
    end
  end

end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string
#  slug       :string
#  show_menu  :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  PARAMS = [:name, :show_menu]

  has_many :posts

  belongs_to :user

  validates :name, :show_menu, presence: true
end

app/models/contact.rb
# == Schema Information
#
# Table name: contacts
#
#  id          :integer          not null, primary key
#  email       :string
#  lastname    :string
#  firstname   :string
#  description :text
#  read        :boolean
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Contact < ActiveRecord::Base
  PARAMS = [:email, :lastname, :firstname, :description]
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id          :integer          not null, primary key
#  title       :string
#  content     :text
#  date_post   :datetime
#  number_view :integer
#  url_image   :string
#  recommend   :boolean
#  public      :boolean
#  description :string
#  slug        :string
#  user_id     :integer
#  category_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  before_create :add_date_post

  PARAMS = [:title, :content, :description, :date_post, :url_image, :recommend, :public, :category_id]

  belongs_to :user
  belongs_to :category

  delegate :name, to: :category, prefix: true, allow_nil: true
  delegate :email, to: :user, prefix: true, allow_nil: true

  validates :title, :description, :content, :category_id, presence: true

  def add_date_post
    self.date_post = DateTime.current
  end
end

app/models/quote.rb
# == Schema Information
#
# Table name: quotes
#
#  id         :integer          not null, primary key
#  content    :string
#  author     :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Quote < ActiveRecord::Base
end

app/models/subcribe.rb
# == Schema Information
#
# Table name: subcribes
#
#  id         :integer          not null, primary key
#  email      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Subcribe < ActiveRecord::Base
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :async,
         :recoverable, :rememberable, :trackable

  has_many :posts
  has_many :categories
  has_one :user_detail

  accepts_nested_attributes_for :user_detail, allow_destroy: true
end

app/models/user_detail.rb
# == Schema Information
#
# Table name: user_details
#
#  id           :integer          not null, primary key
#  first_name   :string
#  last_name    :string
#  phone_number :string
#  address      :string
#  sex          :string
#  user_id      :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class UserDetail < ActiveRecord::Base
  belongs_to :user
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
end

app/controllers/admin/contacts_controller.rb
class Admin::ContactsController < AdminController
  before_action :load_service

  def index
    @q      = @service.condition(params)
    @contacts = @service.index(params[:page])
  end

  def show
    @contact = @service.show_contact(params)
  end

  private
    def load_service
      @service = Admin::ContactService.new
    end
end

app/controllers/admin_controller.rb
class AdminController < ActionController::Base
  before_action :authenticate_user!

  layout 'admin_lte_2'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :show_menu

  def show_menu
    @q     = Post.ransack(params[:q])
    @menus = Category.where(show_menu: '1')
  end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  before_action :load_service

  def index
    @categories = @service.categories
  end

  def show
    @posts = @service.posts.page(params[:page])
  end

  private
    def load_service
      @service = CategoryService.new(params)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :load_service

  def index
    @contact      = @services.new_contact
  end

  def create
    @contact = @services.create_contact(params)
    if @contact.errors.present?
      render 'index'
    else
      flash[:success] = t('.success')
      redirect_to root_path
    end
  end

  private
    def load_service
      @services = ContactService.new
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :load_service

  def index
    @q              = @service.condition(params)
    @posts          = @service.all_post(params)
    @post_recommend = @service.recommend_post
    @post_random    = @service.random_post
    @post_most_view = @service.most_view_post
    @quotes         = @service.quotes
  end

  private
    def load_service
      @service = HomeService.new
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def show
    @post = Post.friendly.find(params[:id])
    @post.update(number_view: @post.number_view.to_i + 1)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/admin/contacts_helper.rb
module Admin::ContactsHelper
end

app/helpers/admin_helper.rb
module AdminHelper
  def gravatar_url(email, size)
    gravatar = Digest::MD5::hexdigest(email).downcase
    url = "http://gravatar.com/avatar/#{gravatar}.png?s=#{size}"
  end

  def active_menu controller_name, name
    controller_name == name ? 'active' : ''
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_menu controller_name, name
    controller_name == name ? 'active' : ''
  end

  def convert_date date
    date.strftime('%b %d, %Y')
  end
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admin/contacts/_search.html.slim
.col-xs-12
  .box.box-warning
    .box-header.with-border
      h3.box-title
        | Search
    =search_form_for @q, url: admin_contacts_path, class: 'form-horizontal' do |f|
      .box-body
        .col-md-6
          .form-group
            label.col-sm-3.control-label
              | Id
            .col-sm-9
              = f.number_field :id_eq, class: 'form-control'
        .col-md-6
          .form-group
            label.col-sm-3.control-label
              | Email
            .col-sm-9
              = f.text_field :email_cont, class: 'form-control'
        .col-md-6
          .form-group
            label.col-sm-3.control-label
              | First Name
            .col-sm-9
              = f.text_field :firstname_cont, class: 'form-control'
        .col-md-6
          .form-group
            label.col-sm-3.control-label
              | Description
            .col-sm-9
              = f.text_field :description_cont, class: 'form-control'
        .col-md-6
          .form-group
            label.col-sm-3.control-label
              | Category
            .col-sm-9
              = f.select :read_eq, [['Read', true], ['Unread', false]], { include_blank: true }, { class: 'form-control' }
      .box-footer
        button.btn.btn-info.pull-left
          | Search

app/views/admin/contacts/index.html.slim
.row
  = render 'search'
  .col-xs-12
    .box
      .box-header
        h3
          | Title
      .box-body
        table#example2.table.table-bordered.table-hover
          thead
            tr
              = content_tag :th, sort_link(@q, :id, t(".id"), default_order: :asc)
              = content_tag :th, sort_link(@q, :email, t(".email"), default_order: :asc)
              = content_tag :th, sort_link(@q, :firstname, t(".firstname"), default_order: :asc)
              = content_tag :th, sort_link(@q, :description, t(".description"), default_order: :asc)
              = content_tag :th, sort_link(@q, :read, t(".read"), default_order: :asc)
              th
          tbody
            - @contacts.each do |contact|
              tr
                td
                  = contact.id
                td
                  = contact.email
                td
                  = "#{contact.firstname} #{contact.lastname}"
                td
                  = contact.description
                td
                  = contact.read? ? 'Read' : 'Unread'
                td
                  .col-sm-4
                    = link_to 'View', admin_contact_path(contact), class: 'btn btn-primary'
.row
  .col-sm-5
    = page_entries_info @contacts, entry_name: ''
  .col-sm-7
    .dataTables_paginate.paging_simple_numbers.pull-right
      = paginate @contacts, theme: 'admin'

app/views/admin/contacts/show.html.slim
.box
  .box-header.with-border
    .row
      .col-md-2
        label
          | Email
      .col-md-10
        = @contact.email
    .row
      .col-md-2
        label
          | Full Name
      .col-md-10
        = "#{@contact.firstname} #{@contact.lastname}"
    .row
      .col-md-2
        label
          | Content
      .col-md-10
        = @contact.description
= link_to "Edit", edit_admin_contact_path(@contact), class: 'btn btn-primary'
= link_to "Back", admin_contacts_path, class: 'btn btn-primary'