config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, path: 'admin', controllers: {
    sessions: 'admin/users/sessions'
  }
  root 'homes#index'

  namespace :admin do
    resources :posts
    resources :categories
    resources :quotes
    resources :contacts
  end

  resources :posts, only: [:index, :show]
  resources :homes, only: [:index]
  resources :contacts, only: [:index, :create]
  resources :category, only: [:index, :show]
  resources :abouts, only: [:index]
  resources :static_pages do
    collection do
      get 'single'
      get 'contact'
      get 'gallery'
    end
  end

end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string
#  slug       :string
#  show_menu  :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  PARAMS = [:name, :show_menu]

  has_many :posts

  belongs_to :user

  validates :name, :show_menu, presence: true
end

app/models/contact.rb
# == Schema Information
#
# Table name: contacts
#
#  id          :integer          not null, primary key
#  email       :string
#  lastname    :string
#  firstname   :string
#  description :text
#  read        :boolean
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Contact < ActiveRecord::Base
  PARAMS = [:email, :lastname, :firstname, :description]
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id          :integer          not null, primary key
#  title       :string
#  content     :text
#  date_post   :datetime
#  number_view :integer
#  url_image   :string
#  recommend   :boolean
#  public      :boolean
#  description :string
#  slug        :string
#  user_id     :integer
#  category_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  before_create :add_date_post

  PARAMS = [:title, :content, :description, :date_post, :url_image, :recommend, :public, :category_id]

  belongs_to :user
  belongs_to :category

  delegate :name, to: :category, prefix: true, allow_nil: true
  delegate :email, to: :user, prefix: true, allow_nil: true

  validates :title, :description, :content, :category_id, presence: true

  def add_date_post
    self.date_post = DateTime.current
  end
end

app/models/quote.rb
# == Schema Information
#
# Table name: quotes
#
#  id         :integer          not null, primary key
#  content    :string
#  author     :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Quote < ActiveRecord::Base
end

app/models/subcribe.rb
# == Schema Information
#
# Table name: subcribes
#
#  id         :integer          not null, primary key
#  email      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Subcribe < ActiveRecord::Base
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :async,
         :recoverable, :rememberable, :trackable

  has_many :posts
  has_many :categories
  has_one :user_detail

  accepts_nested_attributes_for :user_detail, allow_destroy: true
end

app/models/user_detail.rb
# == Schema Information
#
# Table name: user_details
#
#  id           :integer          not null, primary key
#  first_name   :string
#  last_name    :string
#  phone_number :string
#  address      :string
#  sex          :string
#  user_id      :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class UserDetail < ActiveRecord::Base
  belongs_to :user
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  before_action :load_service

  def index
    @q = @service.condition(params)
    @categories = @service.index(params[:page])
  end

  def new
    @category = @service.new_category
  end

  def create
    @category = @service.create_category(params)
    if @category.valid?
      redirect_to admin_categories_path
    else
      render 'new'
    end
  end

  def edit
    @category = @service.find(params[:id])
  end

  def update
    @category = @service.update_category(params)
    if @category.valid?
      redirect_to admin_categories_path
    else
      render 'edit'
    end
  end

  def destroy
    category = @service.destroy_category(params)
    redirect_to admin_categories_path
  end

  private

    def load_service
      @service = Admin::CategoryService.new(current_user, params)
    end
end

app/controllers/admin_controller.rb
class AdminController < ActionController::Base
  before_action :authenticate_user!

  layout 'admin_lte_2'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :show_menu

  def show_menu
    @q     = Post.ransack(params[:q])
    @menus = Category.where(show_menu: '1')
  end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  before_action :load_service

  def index
    @categories = @service.categories
  end

  def show
    @posts = @service.posts.page(params[:page])
  end

  private
    def load_service
      @service = CategoryService.new(params)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :load_service

  def index
    @contact      = @services.new_contact
  end

  def create
    @contact = @services.create_contact(params)
    if @contact.errors.present?
      render 'index'
    else
      flash[:success] = t('.success')
      redirect_to root_path
    end
  end

  private
    def load_service
      @services = ContactService.new
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :load_service

  def index
    @q              = @service.condition(params)
    @posts          = @service.all_post(params)
    @post_recommend = @service.recommend_post
    @post_random    = @service.random_post
    @post_most_view = @service.most_view_post
    @quotes         = @service.quotes
  end

  private
    def load_service
      @service = HomeService.new
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def show
    @post = Post.friendly.find(params[:id])
    @post.update(number_view: @post.number_view.to_i + 1)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
  def gravatar_url(email, size)
    gravatar = Digest::MD5::hexdigest(email).downcase
    url = "http://gravatar.com/avatar/#{gravatar}.png?s=#{size}"
  end

  def active_menu controller_name, name
    controller_name == name ? 'active' : ''
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_menu controller_name, name
    controller_name == name ? 'active' : ''
  end

  def convert_date date
    date.strftime('%b %d, %Y')
  end
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admin/categories/_form.html.slim
.box-body
  = render 'admin/shared/errors', object: @category
  .form-group
    .row
      .col-md-2
        = f.label :name
      .col-md-4
        = f.text_field :name, class: 'form-control'
  .form-group
    .row
      .col-md-2
        = f.label :show_menu
      .col-md-4
        = f.radio_button :show_menu, '1'
        label
          | Yes
        = f.radio_button :show_menu, '0'
        label
          | No
  = f.submit 'Save', class: 'btn btn-primary'
  = link_to "Back", admin_categories_path, class: 'btn btn-primary'

app/views/admin/categories/_search.html.slim
.col-xs-12
  .box.box-warning
    .box-header.with-border
      h3.box-title
        | Search
    =search_form_for @q, url: admin_categories_path, class: 'form-horizontal' do |f|
      .box-body
        .col-md-6
          .form-group
            label.col-sm-3.control-label
              | Name
            .col-sm-9
              = f.text_field :name_cont, class: 'form-control'
      .box-footer
        button.btn.btn-info.pull-left
          | Search

app/views/admin/categories/edit.html.slim
= form_for @category, url: admin_category_path do |f|
  = render 'form', f: f

app/views/admin/categories/index.html.slim
.row
  = render 'search'
  .col-xs-12
    .box
      .box-header
        h3
          | Category
      .box-body
        table#example2.table.table-bordered.table-hover
          thead
            tr
              = content_tag :th, sort_link(@q, :id, t(".id"), default_order: :asc)
              = content_tag :th, sort_link(@q, :name, t(".name"), default_order: :asc)
              th
                | Number Posts
              th
          tbody
            - @categories.each do |category|
              tr
                td
                  = category.id
                td
                  = category.name
                td
                  = category.posts.count
                td.col-sm-3
                  .col-sm-4
                    = link_to 'Edit', edit_admin_category_path(category), class: 'btn btn-primary'
                  .col-sm-4
                    = link_to 'Delete', admin_category_path(category), {:method => :delete, :class=>"btn btn-danger", :type=>"button" , data: { confirm: "Are you sure?" }}
.row
  .col-sm-5
    = page_entries_info @categories, entry_name: ''
  .col-sm-7
    .dataTables_paginate.paging_simple_numbers.pull-right
      = paginate @categories, theme: 'admin'
.row
  .col-xs-12
    = link_to "Create", new_admin_category_path, class: 'btn btn-primary'

app/views/admin/categories/new.html.slim
= form_for @category, url: admin_categories_path do |f|
  = render 'form', f: f